utils::globalVariables(c(
  ".", "adm", "anio", "anios_es", "anios_esc", "asiste",
  "c_res", "clase2", "cmo", "cmo_4d", "coe_tipo", "contrato0", "contrato1",
  "cs_p13_1", "CVE", "d_00_05", "d_06_12", "d_13_17", "d_18m", "d_adm",
  "d_joven1", "d_joven2", "dep", "edad", "edad5", "e_con", "ent",
  "esco_norm", "fac", "family", "familyt", "familyt_lab", "folio2",
  "h_00_05", "h_06_12", "h_13_17", "h_18m", "h_adm", "h_joven1", "h_joven2",
  "i_00_05", "i_06_12", "i_13_17", "i_18m", "i_joven1", "i_joven2",
  "imp_ingocup", "ing7c", "ing_hog", "ing_hog_pc", "ing_hog_pc_sego",
  "ing_ipc", "ingocup", "ingocup_imp", "ipc", "jefa_mujer", "jefe_hombre",
  "log_ingocup_imp", "log_ingocup_imp_imp", "may", "men", "mismatch",
  "mismatch2", "mismatch_raw", "miss_income4", "miss_to_impute",
  "needs_manual_1d", "nondep", "norem_hog", "norem_hog0", "norem_pc",
  "nunca_trabajo", "p11_h1", "p11_h2", "p11_h3", "p11_h4", "p11_h5",
  "p11_h6", "p11_h7", "p11_h8", "p11_m1", "p11_m2", "p11_m3", "p11_m4",
  "p11_m5", "p11_m6", "p11_m7", "p11_m8", "p2h4", "p3coe", "p3i", "p3j",
  "p3j1", "p3k1", "p6b1", "p9_h1", "p9_h2", "p9_h3", "p9_h4", "p9_h5",
  "p9_h6", "p9_h7", "p9_h8", "p9_m1", "p9_m2", "p9_m3", "p9_m4", "p9_m5",
  "p9_m6", "p9_m7", "p9_m8", "p_lab", "p_lab_ratio", "par_c", "par_dic",
  "parentesco", "pos_ocu", "quintil_ing_hog_pc", "quintil_ing_hog_pc_sego",
  "quintil_ing_ind", "quintil_norem_pc", "r_def", "relative", "rela1",
  "rela2", "rela3", "rela4", "rela5", "rela6", "rural", "sex", "sexo",
  "sinco1d", "sinco2d", "sinco3d", "sinco4d", "sinco4d_str", "skill_actual",
  "skill_level", "status_seq", "str_cmo", "t_compras", "t_comun",
  "t_construir", "t_cuidado", "t_dep1", "t_dep2", "t_dep3", "t_estudiar",
  "t_loc", "t_quehacer", "t_reparar", "t_total", "t_total0", "t_total_hrs",
  "t_total_hrs0", "t_traslado", "tam_hog", "temporal", "temporal_seq",
  "tipo_hog", "tipo_hog2", "tipo_hog2_lab", "tipo_hog_lab", "trim",
  "unido", "urb_rur", "zona_econ",  "aplicar_reglas", "cve_ent", "trimestre_n",
  "var_exp_previa", ".trim_n", "periodo_sinco", "sinco3d_nuevo", "cmo2d",
  "cmo3d", "ing_mensual_ipc", ".adulto", ".adulto_ocupado", "hrsocup",
  ".adolescente", ".adulto_no_ocupado", ".mujer", ".hombre",
  ".adolescente_cuida", "n_adultos", "n_adultos_ocupados",
  "n_adultos_no_ocupados", "d_escolar", "todos_adultos_ocupados",
  "algun_adulto_mas_40", "algun_adulto_mas_48",
  "hogar_un_adulto_ocupado", "p3m9", "prest_credito_vivienda",
  "prest_guarderia", "prest_tiempo_cuidados_parentales",
  "prest_fondo_retiro", "prest_seguro_vida", "prest_seguro_medico_privado",
  "prest_prestamos_caja_ahorro", "duracion_precision", "anio_inici",
  "mes_entrevista", "mes_inici", "situacion_estudio_trabajo",
  "no_estudia_no_trabaja", "isco88", "isco88_damian",
  "sinco4d_damian", "calidad_cmo_damian", "n_destinos_cmo_damian",
  "grupo_ocu9_damian", "clase_ocu_damian", "metodo_clase_damian",
  "cobertura_isco88_damian", "cobertura_clase_damian",
  "calificada_damian", "manual_damian", "supervisa_damian",
  "posocup_damian", "tam_est_damian", "clase_egp13_damian",
  "cobertura_egp_damian", "clase_egp7_damian", "clase_alt6_damian",
  "macro_egp4_damian", "macro_solis4_damian", "egp3_damian",
  ".renoe_fila_imputacion", "calidad", "campo_arm10", "campo_arm10_det",
  "campo_arm8", "campo_arm8_det", "clase_isco", "clase_recuperada",
  "clasificador_carrera", "cs_p14_c", "cs_p14_c_canonica",
  "elegible_carrera", "log_ingocup_respaldo", "nivel_carrera", "periodo",
  "sinco2011", "sinco2019",
  "baja_damian", "alta_damian", "autoempleo_damian", "emple7c",
  "cuida_total"
))
